
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry pro1;
	private global::Gtk.Entry pro2;
	private global::Gtk.Entry pro3;
	private global::Gtk.Entry sub;
	private global::Gtk.Entry iva;
	private global::Gtk.Label label3;
	private global::Gtk.Label label2;
	private global::Gtk.Label label1;
	private global::Gtk.Label label5;
	private global::Gtk.Entry total;
	private global::Gtk.Button limpiar;
	private global::Gtk.Button factura;
	private global::Gtk.Label label6;
	private global::Gtk.Label label4;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pro1 = new global::Gtk.Entry ();
		this.pro1.CanFocus = true;
		this.pro1.Name = "pro1";
		this.pro1.IsEditable = true;
		this.pro1.InvisibleChar = '●';
		this.fixed1.Add (this.pro1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.pro1]));
		w1.X = 187;
		w1.Y = 17;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pro2 = new global::Gtk.Entry ();
		this.pro2.CanFocus = true;
		this.pro2.Name = "pro2";
		this.pro2.IsEditable = true;
		this.pro2.InvisibleChar = '●';
		this.fixed1.Add (this.pro2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.pro2]));
		w2.X = 186;
		w2.Y = 49;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pro3 = new global::Gtk.Entry ();
		this.pro3.CanFocus = true;
		this.pro3.Name = "pro3";
		this.pro3.IsEditable = true;
		this.pro3.InvisibleChar = '●';
		this.fixed1.Add (this.pro3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.pro3]));
		w3.X = 187;
		w3.Y = 81;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.sub = new global::Gtk.Entry ();
		this.sub.CanFocus = true;
		this.sub.Name = "sub";
		this.sub.IsEditable = true;
		this.sub.InvisibleChar = '●';
		this.fixed1.Add (this.sub);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.sub]));
		w4.X = 186;
		w4.Y = 145;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.iva = new global::Gtk.Entry ();
		this.iva.CanFocus = true;
		this.iva.Name = "iva";
		this.iva.IsEditable = true;
		this.iva.InvisibleChar = '●';
		this.fixed1.Add (this.iva);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.iva]));
		w5.X = 186;
		w5.Y = 176;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 3");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w6.X = 118;
		w6.Y = 85;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 2");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w7.X = 117;
		w7.Y = 55;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 1");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w8.X = 118;
		w8.Y = 22;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Sub Total");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w9.X = 126;
		w9.Y = 149;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.total = new global::Gtk.Entry ();
		this.total.CanFocus = true;
		this.total.Name = "total";
		this.total.IsEditable = true;
		this.total.InvisibleChar = '●';
		this.fixed1.Add (this.total);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.total]));
		w10.X = 185;
		w10.Y = 208;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.limpiar = new global::Gtk.Button ();
		this.limpiar.CanFocus = true;
		this.limpiar.Name = "limpiar";
		this.limpiar.UseUnderline = true;
		this.limpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
		this.fixed1.Add (this.limpiar);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.limpiar]));
		w11.X = 10;
		w11.Y = 235;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.factura = new global::Gtk.Button ();
		this.factura.CanFocus = true;
		this.factura.Name = "factura";
		this.factura.UseUnderline = true;
		this.factura.Label = global::Mono.Unix.Catalog.GetString ("Facturar");
		this.fixed1.Add (this.factura);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.factura]));
		w12.X = 9;
		w12.Y = 202;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("I.V.A.");
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w13.X = 147;
		w13.Y = 177;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Total");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w14.X = 145;
		w14.Y = 212;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.limpiar.Clicked += new global::System.EventHandler (this.OnLimpiarClicked);
		this.factura.Clicked += new global::System.EventHandler (this.OnFacturaClicked);
	}
}
